# docker-compose.yml
version: '3'
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - zooting_net

networks:
  zooting_net:
    driver: bridge