version: "3"
services:
  springboot:
    container_name: zooting-api
    image: duckbill413/zooting-docker-api:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - zooting_net
    volumes:
      - /home/ec2-user/logs:/logs

  redis:
    image: redis:alpine
    container_name: zooting-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6800:6800"
    networks:
      - zooting_net
    restart: always

networks:
  zooting_net:
    driver: bridge