version: "3"
services:
  nginx:
    container_name: zooting-nginx
    image: nginx
    restart: always
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - zooting_net
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  springboot:
    container_name: zooting-api
    image: duckbill413/zooting-docker-api:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - zooting_net
    volumes:
      - /home/ec2-user/logs:/logs

  redis:
    image: redis:alpine
    container_name: zooting-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - zooting_net
    restart: always

networks:
  zooting_net:
    driver: bridge